
import React, { useState } from "react";
import PageLayout from "@/components/layout/PageLayout";
import ChatMessage from "@/components/chat/ChatMessage";
import ChatInput from "@/components/chat/ChatInput";
import { chatMessages as initialMessages } from "@/data/mockData";

const ChatPage = () => {
  const [messages, setMessages] = useState(initialMessages);

  const handleSendMessage = (message: string) => {
    // Add user message
    const userMessage = {
      id: messages.length + 1,
      content: message,
      isUser: true,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };
    
    setMessages((prev) => [...prev, userMessage]);
    
    // Simulate AI response after a short delay
    setTimeout(() => {
      const aiResponse = {
        id: messages.length + 2,
        content: "I'm your AI tutor assistant. This is a placeholder response that would normally be generated by a real AI model based on your course materials.",
        isUser: false,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      };
      
      setMessages((prev) => [...prev, aiResponse]);
    }, 1000);
  };

  return (
    <PageLayout title="AI Chat Assistant">
      <div className="flex flex-col h-[calc(100vh-8rem)]">
        <div className="flex-1 overflow-y-auto px-1 py-2">
          {messages.map((message) => (
            <ChatMessage
              key={message.id}
              content={message.content}
              isUser={message.isUser}
              timestamp={message.timestamp}
            />
          ))}
        </div>
        
        <div className="pt-2 pb-4">
          <ChatInput onSendMessage={handleSendMessage} />
        </div>
      </div>
    </PageLayout>
  );
};

export default ChatPage;
